### ISSUE TITLE
Regular HTML Tags instead of select

### ISSUE THREAD

**Issue by ev3nst** [jakezatecky/react-dual-listbox#213]
When styling option background color when clicked on cannot be changed with css afaik.

![highlight](https://user-images.githubusercontent.com/16917285/205433818-04344478-ab80-4639-a134-dad9a7c8f007.png)

So far i have tried the following;
````css
select.rdl-control:focus option,
select.rdl-control:focus option:checked,
select.rdl-control:focus option:active,
select.rdl-control:focus option:visited,
select.rdl-control:focus option::selection,
select.rdl-control:focus option[selected],
select.rdl-control:focus-within option:checked,
select.rdl-control:focus-within option:active,
select.rdl-control:focus-within option:visited,
select.rdl-control:focus-within option::selection,
select.rdl-control:focus-within option[selected],
select.rdl-control:visited option,
select.rdl-control:visited option:checked,
select.rdl-control:visited option:active,
select.rdl-control:visited option:visited,
select.rdl-control:visited option::selection,
select.rdl-control:visited option[selected],
select.rdl-control:hover option:checked,
select.rdl-control:hover option:active,
select.rdl-control:hover option:visited,
select.rdl-control:hover option::selection,
select.rdl-control:hover option[selected],
select.rdl-control:active option:checked,
select.rdl-control:active option:active,
select.rdl-control:active option:visited,
select.rdl-control:active option::selection,
select.rdl-control:active option[selected],
select.rdl-control option:checked,
select.rdl-control option:checked:active,
select.rdl-control option:checked:visited,
select.rdl-control option:checked:hover,
select.rdl-control option:checked:focus,
select.rdl-control option:checked:focus-visible,
select.rdl-control option:checked:focus-within,
select.rdl-control option:visited,
select.rdl-control option:active,
select.rdl-control option:focus,
select.rdl-control option:hover,
select.rdl-control option:target,
select.rdl-control option:focus-visible,
select.rdl-control option:focus-within,
select.rdl-control option::selection {
    background-color: #000 !important;
    outline: none !important;
    box-shadow: none !important;
}
````
If my example is true i think it would be a lot better to have divs instead of select and option. Not only for styling but drag & drop and other features could be implemented easier i think.
