### ISSUE TITLE
how to disable or hide conditionally MoveLeft and MoveAllLeft icons

### ISSUE THREAD

**Issue by Kranthi32** [jakezatecky/react-dual-listbox#296]

**Comment by jakezatecky** [comment]
While there is no property to hide or disable these icons, you can easily hide them with CSS.

If you want to _just_ hide the icons moving items to the left, you can do the following:

``` css
.rdl-actions-to-available {
  display: none;
}

/* Align the remaining actions to the center */
.rdl-actions {
  align-self: center; /* or use `flex-start` */
}
```

If you want to hide all actions, not just the ones moving items to the available list, you can do the following:

``` css
.rdl-actions {
  display: none;
}
```
